### ISSUE TITLE
Don't work if the height change

### ISSUE THREAD

**Issue by groomain** [docccdev/react-overflow-scrolling#3]
Hi,

I have a problem. If the height of the div contained inside change, the scroll is still blocked.

Any ideas ?
Regards

**Comment by docccdev** [comment]
Hi, please show a live example. It seems like a normal behavior to block scrolling to the top always regardless of the content

**Comment by groomain** [comment]
On mobile if the content change and will be too big the scroll appeared but you can't scroll at all.
If the content can be scrolled at the initialization it's working.

**Comment by docccdev** [comment]
What css value of `overflow` is set for the scroll block?

**Comment by docccdev** [comment]
See example with dynamic content in sidebar, it's work for me on latest iOS Safari

https://evokit.net/demo/react-overflow-scrolling/

If this demo doesn't work for you, please give me more information about your browser, OS version and usage code

**Comment by groomain** [comment]
https://stackoverflow.com/a/37916143/3828682

It's because of the -webkit-overflow-scrolling: touch;
